version: '3'

services:
  nodejs:
    build:
    #fill out the configuration here
      context: ./
      dockerfile: Dockerfile
    
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "80:8080"
    networks:
      - app-network
  
  #the nginx configuration is given below
  #the website will run on localhost:80 
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodejs
    networks:
      - app-network

volumes:
  web-root:
    driver: local
    driver_opts:
      type: none
      #fill out your absolute path to your folder here
      device: ./
      o: bind

networks:
  app-network:
    driver: bridge 